'use client';

// ============================================================================
// RS ZEVAR ERP — Loadsheets History Page (May 6 2026)
// Route: /orders/loadsheets
// ----------------------------------------------------------------------------
// Browse all past loadsheets. Click any row → opens print page (where user
// can reprint without regenerating).
//
// Search: by loadsheet number ya generated_by name.
// Pagination: 50 per page.
// ============================================================================

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useUser } from '@/context/UserContext';

const gold = 'var(--gold)';
const bg = 'var(--bg)';
const card = 'var(--bg-card)';
const border = 'var(--border)';
const text1 = '#e5e5e5';
const text2 = 'var(--text2)';

const fmt = (n) => 'Rs ' + Math.round(Number(n || 0)).toLocaleString('en-PK');

function formatDateTime(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  const sameDay = (a, b) =>
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate();

  const time = d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  if (sameDay(d, today))      return `Today, ${time}`;
  if (sameDay(d, yesterday))  return `Yesterday, ${time}`;

  return d.toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export default function LoadsheetsHistoryPage() {
  const router = useRouter();
  const { can } = useUser();
  const canView = can('orders.view');

  const [loadsheets, setLoadsheets] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [page, setPage] = useState(0);
  const limit = 50;

  // Debounce search input
  useEffect(() => {
    const t = setTimeout(() => setDebouncedSearch(search), 350);
    return () => clearTimeout(t);
  }, [search]);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        limit: String(limit),
        offset: String(page * limit),
      });
      if (debouncedSearch) params.set('search', debouncedSearch);

      const r = await fetch(`/api/loadsheets?${params}`);
      const d = await r.json();
      if (d.success) {
        setLoadsheets(d.loadsheets || []);
        setTotal(d.total || 0);
      }
    } catch (e) {
      console.error('Loadsheets fetch failed:', e.message);
    }
    setLoading(false);
  }, [page, debouncedSearch]);

  useEffect(() => { load(); }, [load]);

  // Reset page when search changes
  useEffect(() => { setPage(0); }, [debouncedSearch]);

  if (!canView) {
    return (
      <div style={{ background: bg, minHeight: '100vh', color: text1, padding: 40 }}>
        <h1 style={{ color: gold }}>Access Denied</h1>
      </div>
    );
  }

  const totalPages = Math.ceil(total / limit);

  return (
    <div style={{ background: bg, minHeight: '100vh', color: text1 }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '20px 24px 60px' }}>

        {/* Header */}
        <div style={{ marginBottom: 20 }}>
          <Link href="/orders" style={{ color: text2, fontSize: 13, textDecoration: 'none' }}>
            ← Orders
          </Link>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 8 }}>
            <div>
              <h1 style={{
                color: gold, fontSize: 26, margin: '0 0 4px',
                fontWeight: 700, letterSpacing: -0.5,
              }}>
                📋 Loadsheets History
              </h1>
              <p style={{ color: text2, fontSize: 13, margin: 0 }}>
                Past dispatch reports — view, reprint, search.
                {!loading && total > 0 && <span> · {total} total</span>}
              </p>
            </div>
            <Link href="/orders/dispatch-scan" style={{
              padding: '10px 16px', fontSize: 13, fontWeight: 600,
              background: gold, color: 'var(--text)',
              border: 'none', borderRadius: 6, textDecoration: 'none',
            }}>
              📡 New Scan Session
            </Link>
          </div>
        </div>

        {/* Search */}
        <div style={{ marginBottom: 16 }}>
          <input
            type="text"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search loadsheet number ya generated by..."
            style={{
              width: '100%', maxWidth: 420, padding: '10px 14px', fontSize: 13,
              background: 'var(--bg)', color: text1,
              border: `1px solid ${border}`, borderRadius: 6, outline: 'none',
            }}
          />
        </div>

        {/* List */}
        <div style={{
          background: card, border: `1px solid ${border}`, borderRadius: 8,
          overflow: 'hidden',
        }}>
          {/* Table header */}
          <div style={{
            padding: '12px 18px',
            borderBottom: `1px solid ${border}`,
            display: 'grid',
            gridTemplateColumns: '180px 160px 1fr 80px 110px 80px',
            gap: 14, alignItems: 'center',
            fontSize: 11, color: text2, fontWeight: 600,
            letterSpacing: 0.5, textTransform: 'uppercase',
          }}>
            <div>Loadsheet #</div>
            <div>Date</div>
            <div>Generated By</div>
            <div style={{ textAlign: 'right' }}>Parcels</div>
            <div style={{ textAlign: 'right' }}>Total COD</div>
            <div style={{ textAlign: 'right' }}>Action</div>
          </div>

          {/* Rows */}
          {loading ? (
            <div style={{ padding: 40, textAlign: 'center', color: text2 }}>
              Loading...
            </div>
          ) : loadsheets.length === 0 ? (
            <div style={{ padding: 60, textAlign: 'center', color: text2 }}>
              {debouncedSearch
                ? `Koi loadsheet match nahi ki "${debouncedSearch}" ke saath`
                : 'Abhi tak koi loadsheet generate nahi hui'}
            </div>
          ) : (
            loadsheets.map((ls, i) => (
              <Link
                key={ls.id}
                href={`/orders/loadsheets/${ls.id}/print`}
                style={{
                  display: 'grid',
                  gridTemplateColumns: '180px 160px 1fr 80px 110px 80px',
                  gap: 14, alignItems: 'center',
                  padding: '14px 18px',
                  borderBottom: i < loadsheets.length - 1 ? `1px solid ${border}` : 'none',
                  fontSize: 13, color: text1, textDecoration: 'none',
                  transition: 'background 0.15s',
                }}
                onMouseEnter={e => e.currentTarget.style.background = '#1a1a1a'}
                onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
              >
                <div style={{
                  fontFamily: 'monospace', fontSize: 12, color: gold, fontWeight: 600,
                }}>
                  {ls.loadsheet_number}
                </div>
                <div style={{ color: text1 }}>
                  {formatDateTime(ls.generated_at)}
                </div>
                <div style={{ color: text1 }}>
                  {ls.generated_by || <span style={{ color: text2 }}>—</span>}
                  {ls.notes && (
                    <div style={{ fontSize: 11, color: text2, marginTop: 2, fontStyle: 'italic' }}>
                      {ls.notes}
                    </div>
                  )}
                </div>
                <div style={{ textAlign: 'right', fontWeight: 600 }}>
                  {ls.total_parcels}
                </div>
                <div style={{ textAlign: 'right', color: gold, fontWeight: 600 }}>
                  {fmt(ls.total_cod)}
                </div>
                <div style={{ textAlign: 'right', fontSize: 11, color: gold }}>
                  🖨️ View
                </div>
              </Link>
            ))
          )}
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div style={{
            marginTop: 16, display: 'flex', gap: 10, alignItems: 'center',
            justifyContent: 'center',
          }}>
            <button
              onClick={() => setPage(p => Math.max(0, p - 1))}
              disabled={page === 0}
              style={{
                padding: '8px 14px', fontSize: 13,
                background: 'var(--bg-card)', color: text1,
                border: `1px solid ${border}`, borderRadius: 6,
                cursor: page === 0 ? 'not-allowed' : 'pointer',
                opacity: page === 0 ? 0.4 : 1,
              }}
            >
              ← Previous
            </button>
            <span style={{ color: text2, fontSize: 13 }}>
              Page {page + 1} of {totalPages}
            </span>
            <button
              onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
              disabled={page >= totalPages - 1}
              style={{
                padding: '8px 14px', fontSize: 13,
                background: 'var(--bg-card)', color: text1,
                border: `1px solid ${border}`, borderRadius: 6,
                cursor: page >= totalPages - 1 ? 'not-allowed' : 'pointer',
                opacity: page >= totalPages - 1 ? 0.4 : 1,
              }}
            >
              Next →
            </button>
          </div>
        )}

      </div>
    </div>
  );
}
